### ISSUE TITLE
Folder still expands on click

### ISSUE THREAD

**Issue by replete** [alangrainger/obsidian-folder-notes#2]
Ideally, clicking a folder title in the file explorer would only expand IF there is a folder note, but for me with Obsidian 1.1.5, it still opens.

```js
                // Stop the normal folder click executing
                event.stopImmediatePropagation()
```

Has this stopped working?

**Comment by replete** [comment]
![screencast 2023-02-26 00-41-48](https://user-images.githubusercontent.com/812139/221386221-3a719448-a0f6-4f78-a171-88447f11cb5c.gif)

**Comment by alangrainger** [comment]
This plugin was obsoleted by: https://obsidian.md/plugins?id=folder-notes

I should have archived this project - I am doing so now.
